### PR TITLE
Create requirements file

### PR DESCRIPTION
**Pull request by karx1**
This allows people to get their development environments up and running quickly and not have to track down all the dependencies to get the server up and running.

This requirements file is not meant to be completely done in any way, and modifications to this PR are welcome.

### CODE REVIEW

**Comment by arthtyagi** [comment]
there's technically no need of a `requirements.txt` file since there's already a Pipfile.
To get started quick, just do `pipenv install` and that's it. ( Given you first activate the pipenv environment using `pipenv shell`).

**Comment by arthtyagi** [comment]
P.S Create a PR to the `dev` branch from the next time.
`pip3 freeze > requirements.txt` is the command you're expected to use just to you know.

**Comment by karx1** [comment]
Alright, i'll make it to the dev branch next time. That's what I did, but first I had to actually get all the dependencies installed. Otherwise, it would have made an empty file.

**Comment by karx1** [comment]
Another thing, `pip freeze` puts *all* of the dependencies (even dependencies of dependencies) in the requirements.txt file. This is unnecessary, because just putting the "top-level" dependencies would still install all the other ones automatically.

**Comment by karx1** [comment]
@arthtyagi lol, the new requirements file that you made doesn't actually contain any of the requirements the app needs to run. It doesn't even contain django!

**Comment by arthtyagi** [comment]
might've forgotten to enable the pipenv, check again.

**Comment by karx1** [comment]
Yep, it works now.

**Pull request merged**
