### PR TITLE
#29 - [IMPROVEMENT] - Made code tabs in fusion resizable

### PR DESCRIPTION
**Pull request by Suniti13**
Your PR should be for a corresponding issue. If the issue doesn't exist yet, create that issue and mention the issue in your PR.

Add one of the following prefixes for your PR:

    [ [ISSUE-LABEL] - FEATURE ]
    [ [ISSUE-LABEL] - FIX ]
    [ [ISSUE-LABEL] - IMPROVEMENT ]

Your PR should contain a description of the changes you made.
The description should be within 250 words. Please try to follow this word limit.

**In raising this pull request, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/the-domecode/domecode-opensource/blob/master/contribution.md).
- [x] I have checked that another pull request for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**Am I familiar with the tech stack of this project? (Important for PRs that have code changes)**

- [x] Yes
- [] No.

If yes, please mention the back-end framework used in this project. - {Django}

**Have I contributed before to DomeCode? (req.)**

- [ ] Yes, once.
- [ ] Yes, more than once but not a lot.
- [ ] Yes, extensively.
- [x] No.

**Have I used DomeCode? (req.)**

- [ ] Not a lot.
- [ ] Extensively.
- [x] Nope.
---

I made style changes so that the code tabs in fusion can be resized.
They can be resized by dragging the boxes from bottom right corner.
#29

### CODE REVIEW

**Comment by karx1** [comment]
Please make your issue be something like #3 - Improvement instead of just improvement.

**Comment by karx1** [comment]
Also, shouldn't it be `resize: both;` so we can resize horizontally as well as vertically? Currently your code makes it only resizable vertically. Otherwise, great work!

**Comment by Suniti13** [comment]
I don't think resizing horizontally would be nice here because when width is reduced just white space remains. If the width is increased, it goes beyond the left container and gets over the right container, hiding the content on the right. In both cases it doesn't look nice. If you still want me to make it resize both vertically and horizontally, I will gladly do so.

**Comment by karx1** [comment]
I think in order to fix that issue you have to set `overflow: auto;` in
order for it to work correctly.

**Comment by Suniti13** [comment]
That helped. Thanks. I will update it.

**Comment by arthtyagi** [comment]
It works. However, only partially. The tabs on the left ( the ones with code are resizeable ) but it's clearly not obvious where to drag them from anymore once they are dragged from the bottom right. 
I tried resizing them, worked for the first time. But then there was whitespace below the JavaScript code tab that remained until the page was refreshed.

Also, I'm able to resize the unwanted tab by dragging from the middle of the bottom tab.

image
The whitespace below JSCode doesn't go away. And upon dragging from the middle ( a bit to the right tho ) of CSS Code, the HTML code gets resized instead. 

And sometimes this happens :

[Screen Recording 2020-10-04 at 10.25.09 PM.zip](https://github.com/The-Domecode/domecode-opensource/files/5323684/Screen.Recording.2020-10-04.at.10.25.09.PM.zip)

**Comment by karx1** [comment]
@Suniti13 any updates?

**Comment by arthtyagi** [comment]
Well, there hasn't been any update from the author @Suniti13 so I'm closing this ultimately.

**Pull request closed without merging**
